# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teacherlook.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 703)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("teacher.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 10, 2)
        self.keshu = QtWidgets.QLineEdit(self.widget)
        self.keshu.setObjectName("keshu")
        self.gridLayout.addWidget(self.keshu, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.nameedit = QtWidgets.QLineEdit(self.widget)
        self.nameedit.setObjectName("nameedit")
        self.gridLayout.addWidget(self.nameedit, 1, 1, 1, 1)
        self.jgID = QtWidgets.QLineEdit(self.widget)
        self.jgID.setObjectName("jgID")
        self.gridLayout.addWidget(self.jgID, 0, 1, 1, 1)
        self.xueke = QtWidgets.QLineEdit(self.widget)
        self.xueke.setObjectName("xueke")
        self.gridLayout.addWidget(self.xueke, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.shanchu = QtWidgets.QPushButton(self.widget)
        self.shanchu.setObjectName("shanchu")
        self.gridLayout.addWidget(self.shanchu, 1, 2, 1, 1)
        self.add_new = QtWidgets.QPushButton(self.widget)
        self.add_new.setObjectName("add_new")
        self.gridLayout.addWidget(self.add_new, 2, 2, 1, 1)
        self.change = QtWidgets.QPushButton(self.widget)
        self.change.setObjectName("change")
        self.gridLayout.addWidget(self.change, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.t_status = QtWidgets.QPushButton(self.widget)
        self.t_status.setObjectName("t_status")
        self.gridLayout.addWidget(self.t_status, 5, 2, 1, 1)
        self.t_works = QtWidgets.QPushButton(self.widget)
        self.t_works.setObjectName("t_works")
        self.gridLayout.addWidget(self.t_works, 6, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_open = QtWidgets.QAction(MainWindow)
        self.file_open.setObjectName("file_open")
        self.file_save = QtWidgets.QAction(MainWindow)
        self.file_save.setObjectName("file_save")
        self.menu.addAction(self.file_save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "教师管理系统"))
        self.label_3.setText(_translate("MainWindow", "教工号"))
        self.label_5.setText(_translate("MainWindow", "一周几节课"))
        self.label_4.setText(_translate("MainWindow", "所授学科"))
        self.label.setText(_translate("MainWindow", "维护"))
        self.shanchu.setText(_translate("MainWindow", "删除"))
        self.add_new.setText(_translate("MainWindow", "添加"))
        self.change.setText(_translate("MainWindow", "修改"))
        self.label_2.setText(_translate("MainWindow", "查询"))
        self.t_status.setText(_translate("MainWindow", "教师任课情况"))
        self.t_works.setText(_translate("MainWindow", "工作量统计"))
        self.label_6.setText(_translate("MainWindow", "姓名"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.file_open.setText(_translate("MainWindow", "文件读取"))
        self.file_save.setText(_translate("MainWindow", "文件备份"))
